### PR TITLE
Implements $ifnull expression operator in for the aggregate command.

### PR DESCRIPTION
**Pull request by vladlosev**
@parkr @bigthyme Please take a look at this one.

I am particularly interested in your opinion on whether `validateExpression` and `getExpressionValue` - they both walk over the expression tree and thus have very similar structure. Should they be merged into a single method or kept separate? And if it's the latter, what's the best way to keep them in sync, in your opinion?

### CODE REVIEW

**Comment by Phraxos** [comment]
:shipit: This is great! :+1:

**Comment by bigthyme** [comment]
keep separate, lgtm.

**Comment by vladlosev** [comment]
Thanks for looking!

**Pull request merged**
