### PR TITLE
Improves projection in find.

### PR DESCRIPTION
**Pull request by vladlosev**
@parkr @corydobson This takes a better implementation of projections from #15 and plugs it into `find`.

### CODE REVIEW

**Comment by vladlosev** [comment]
@MrNice, will you lend your :eyes: to this PR?

**Comment by MrNice** [comment]
@vladlosev Checking over this now, I'm unfamiliar with pulling only certain keys from mongo

**Comment by parkr** [comment]
:+1:

**Comment by MrNice** [comment]
:+1:
Took me a while to get all of the context for this PR, sorry about that.

**Comment by vladlosev** [comment]
Thanks for the review!

**Comment by MrNice** [comment]
Np ping me any time. I kinda need this module personally heh

**Pull request merged**
